# Generated by Django 4.2 on 2025-01-07 06:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_age_user_bio_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مردی'), ('female', 'زن')], max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'کاربر عادی'), ('admin', 'ادمین'), ('finance', 'مدیر مالی')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='unknown', help_text='لطفا شماره تلفن خود را  وارد کنید', max_length=11, null=True, unique=True, validators=[core.models.validate_phone_number]),
        ),
    ]
