# Generated by Django 5.1.6 on 2025-03-02 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_alter_task_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
