# Generated by Django 4.2 on 2025-02-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('P', 'Published'), ('UR', 'Under Review'), ('R', 'Rejected')], default='UR', max_length=2),
        ),
    ]
